### ISSUE TITLE
The code of randlanet with CGA

### ISSUE THREAD

**Issue by yangpanquan** [MCG-NJU/CGA-Net#2]
Hi, I'm interested in your idea. So, the CGA module is added to the end of coarse segmentation,is it all right?Besides, as you see, ther is no example of randlanet. And I see there is a difference between CloseLook3D and randlanet. So, can you mind to upload the code of randlanet with cganet?

Best

**Comment by inspirelt** [comment]
Yes, this module is appended after the coarse segmentation. The example of RandLA-Net can be obtained following similar steps with CloserLook3D. I will organize a version tonight and release it tomorrow.

**Comment by yangpanquan** [comment]
Ok, I get it! Thank you very much for your effort.

Best!

**Comment by whuhxb** [comment]
@yangpanquan 
Hi, I have seen you also need the source code of CGA-Net. Have you run the code released by the author?
